config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resources :bands
  resources :albums
  resources :tracks

  resource :session, only: [:create, :destroy, :new]

  root 'sessions#new'

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  style      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :string           not null
#

class Album < ActiveRecord::Base
  validates :name, :band_id, :style, presence: true

  has_many :tracks
  belongs_to :band
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  album_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  name       :string
#  album_id   :integer          not null
#  lyrics     :text
#  style      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ActiveRecord::Base
  validates :album_id, :style, :name, presence: true

  belongs_to :album
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :email, :session_token, uniqueness: true, presence: true
  validates :password_digest, presence: true

  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom::base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to albums_url(@album)
    else
      flash[:errors] = "Need more information!"
      render :new
    end
  end

  def show
    @album = Album.find_by_id(params[:album][:id])
    render :show
  end

  private

  def album_params
    params.require(:album).permit(:name, :band_id, :style)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  private
  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = "You must enter a band name!"
      render :new
    end
  end

  def show
    @band = Band.find_by_id(params[:id])
    render :show
      # flash[:errors] = "You must be logged in to view your band page!"
      # redirect_to new_session_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #before_action :require_no_user!, only: [:create, :new]

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if @user.nil?
      flash[:errors] = "Incorrect username and/or password"
      render :new
    else
      @user.reset_session_token!
      session[:session_token] = @user.session_token
      login_user!(@user)
      redirect_to user_url(@user)
    end
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = "Invalid username/password!"
      render :new
    end
  end

  def show
    @user = current_user
    if !@user.nil? && @user == User.find_by_id(params[:id])
      render :show
    else
      flash[:errors] = "You must be logged in to view your user page!"
      redirect_to new_session_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/new.html.erb
<h1>Add a new album</h1>

<br>

<form action="<%= albums_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="album_band_id">Band</label>
  <select name="album[band_id]" id="albm_band_id">
    <option></option>
    <% Band.all.each do |band| %>
      <% selected = @album.band_id == band.id %>
      <option <%= selected ? "selected" : "" %>
              value="<%= band.id %>">
        <%= band.name %>
      </option>
    <% end %>
  </select>
  <br>

  <label for="album_name">Title
    <input type="text" name="album[name]" id="album_name"
      value="<%= @album.name %>">
  <br>

  <label for="band_style_studio"
  <input type="radio" name="band[style]" value="studio" id="band_style_studio"
      <%= @album.style == "studio" ? "checked" : "" %>>Studio</label>
  <label for="band_style_live"
  <input type="radio" name="band[style]" value="live" id="band_style_live"
      <%= @album.style == "live" ? "checked" : "" %>>Live</label>
  <br>
  
  <input type="submit">
</form>

app/views/bands/new.html.erb
<h1>Create a new band:</h1>

<form action="<%= bands_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for "band_name">Band Name
    <input type="text" name="band[name]" id="name">
  </label>
  <br>

  <input type="submit">
</form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<h3>A marvelous band!</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:errors] %>
<% unless current_user.nil? %>
<h3>Logged in as: <%= current_user.email %></h3><br>
<%= button_to "Logout", session_url, method: :delete %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Signup Here!</h1>

<form action="<%= users_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <label for="user_email">Email Address
      <input type="text" name="user[email]" id="email">
    </label>
  <br>

  <label for="user_password">Password
    <input type="password" name="user[password]" id="user_password">
  </label>
  <br>

  <input type="submit">
</form>

<br>
<%= link_to "Sign in to an existing account", new_session_url, method: :get %>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.email %>!</h1>
<br>

<%= link_to "Add a New Band", new_band_url, method: :get %>
<br>
<%= link_to "Add a New Album", new_album_url, method: :get %>
<br>
<%= link_to "Add a New Track", new_track_url, method: :get %>